version: '2'

services:
    
    proxy:
        build: .
        ports:
            - "127.0.0.1:13194:13194"
            #- "127.0.0.1:13194:13194/udp"
        # UDP did not work, probably because the source port changes all the time
        #command: -v UDP4-RECVFROM:13194,fork UDP4-SENDTO:172.17.0.1:1194
        command: TCP-LISTEN:13194,fork TCP:172.17.0.1:1194
        restart: always

    openvpn:
        image: kylemanna/openvpn
        volumes:
            - .:/local
            - ./config:/etc/openvpn
        network_mode: host
        cap_add:
            - NET_ADMIN
        environment:
            dest: docker-for-mac.ovpn
            DEBUG: '1'
        command: /local/helpers/run.sh
        restart: always

